version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-react-app
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-service.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-service.sh
      timeout: 300
      runas: ec2-user
